/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export type EmailAddress = string[];
/**
 * The percentage of discount for the current subscription. 0.1 will stand for 10% discount, -0.1 will stand for 10% surcharge
 */
export type DiscountPercentage = number;
export type BillingCode = string;
export type BillingCycle = string;
export type CanSelfServe = boolean;
export type IsLegacy = boolean;
/**
 * Monthly price without discounts or plan addons included
 */
export type MonthlyPrice = number;
/**
 * Annual price without discounts or plan addons included
 */
export type AnnualPrice = number;
export type StartsOnDate = string;
export type EndsOnDate = string;
export type Industry = string;
export type Location = string;
export type StageOfBusiness = string;
export type Description = string;
/**
 * Calculated with the formula: monthlyPrice * (1 - discountPercentage). This number is excluding plan addons
 */
export type SumMonthlyPrice = number;
/**
 * Calculated with the formula: annualPrice * (1 - discountPercentage). This number is excluding plan addons
 */
export type SumAnnualPrice = number;

export interface AccountData {
	type?: 'Lead' | 'Customer';
	email?: EmailAddress;
	discountPercentage?: DiscountPercentage;
	billingCode?: BillingCode;
	billingCycle?: BillingCycle;
	canSelfServe?: CanSelfServe;
	isLegacy?: IsLegacy;
	monthlyPrice?: MonthlyPrice;
	annualPrice?: AnnualPrice;
	startsOnDate?: StartsOnDate;
	endsOnDate?: EndsOnDate;
	industry?: Industry;
	location?: Location;
	stageOfBusiness?: StageOfBusiness;
	description?: Description;
	SumMonthlyPrice?: SumMonthlyPrice;
	SumAnnualPrice?: SumAnnualPrice;
	[k: string]: unknown;
}

export type AccountContractDefinition = ContractDefinition<AccountData>;

export type AccountContract = Contract<AccountData>;
