/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface ActionData {
	extends?: string;
	filter?: {
		[k: string]: unknown;
	};
	arguments: {
		/**
		 * This interface was referenced by `undefined`'s JSON-Schema definition
		 * via the `patternProperty` "^[a-z0-9]+$".
		 */
		[k: string]: {
			[k: string]: unknown;
		};
	};
	[k: string]: unknown;
}

export type ActionContractDefinition = ContractDefinition<ActionData>;

export type ActionContract = Contract<ActionData>;
