/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface ActionRequestData {
	executed?: boolean;
	results?: {
		error: boolean;
		data:
			| {
					[k: string]: unknown;
			  }
			| string
			| number
			| boolean
			| unknown[]
			| null;
		[k: string]: unknown;
	};
	epoch: number;
	timestamp: string;
	context: {
		id: string;
		[k: string]: unknown;
	};
	originator?: string;
	actor: string;
	action: string;
	input: {
		id: string;
		[k: string]: unknown;
	};
	arguments: {
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export type ActionRequestContractDefinition =
	ContractDefinition<ActionRequestData>;

export type ActionRequestContract = Contract<ActionRequestData>;
