/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export type FlowdockThreadURL = string;
export type Status = 'open' | 'ongoing' | 'closed' | 'archived';

export interface BrainstormTopicData {
	reporter?: string;
	category: string;
	description: string;
	flowdockThreadUrl?: FlowdockThreadURL;
	participants?: unknown[];
	mentionsUser?: unknown[];
	alertsUser?: unknown[];
	mentionsGroup?: unknown[];
	alertsGroup?: unknown[];
	status: Status;
	[k: string]: unknown;
}

export type BrainstormTopicContractDefinition =
	ContractDefinition<BrainstormTopicData>;

export type BrainstormTopicContract = Contract<BrainstormTopicData>;
