/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export type ChartingLibrary = 'plotly';

export interface ChartConfigurationData {
	description?: string;
	chartingLibrary: ChartingLibrary;
	settings: string;
	[k: string]: unknown;
}

export interface ChartConfigurationContractDefinition
	extends ContractDefinition<ChartConfigurationData> {}

export interface ChartConfigurationContract
	extends Contract<ChartConfigurationData> {}
