/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface ContractRepositoryData {
	base_slug: string;
	base_type: string;
	[k: string]: unknown;
}

export interface ContractRepositoryContractDefinition
	extends ContractDefinition<ContractRepositoryData> {}

export interface ContractRepositoryContract
	extends Contract<ContractRepositoryData> {}
