/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface ExecuteData {
	timestamp: string;
	originator?: string;
	target: string;
	actor: string;
	payload: {
		action: string;
		card: string;
		timestamp: string;
		error: boolean;
		data:
			| {
					[k: string]: unknown;
			  }
			| string
			| number
			| boolean
			| unknown[]
			| null;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export interface ExecuteContractDefinition
	extends ContractDefinition<ExecuteData> {}

export interface ExecuteContract extends Contract<ExecuteData> {}
