/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface ExternalEventData {
	source: string;
	headers: {
		[k: string]: unknown;
	};
	payload:
		| {
				[k: string]: unknown;
		  }
		| string;
	[k: string]: unknown;
}

export interface ExternalEventContractDefinition
	extends ContractDefinition<ExternalEventData> {}

export interface ExternalEventContract extends Contract<ExternalEventData> {}
