/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface ExternalEventData {
	source: string;
	headers: {
		[k: string]: unknown;
	};
	payload:
		| {
				[k: string]: unknown;
		  }
		| string;
	[k: string]: unknown;
}

export type ExternalEventContractDefinition =
	ContractDefinition<ExternalEventData>;

export type ExternalEventContract = Contract<ExternalEventData>;
