/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface FaqData {
	topic?: string;
	answer?: string;
	[k: string]: unknown;
}

export type FaqContractDefinition = ContractDefinition<FaqData>;

export type FaqContract = Contract<FaqData>;
