/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface FaqData {
	topic?: string;
	answer?: string;
	[k: string]: unknown;
}

export interface FaqContractDefinition extends ContractDefinition<FaqData> {}

export interface FaqContract extends Contract<FaqData> {}
