/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface GroupData {
	description?: string;
	namespace?: string;
	[k: string]: unknown;
}

export interface GroupContractDefinition
	extends ContractDefinition<GroupData> {}

export interface GroupContract extends Contract<GroupData> {}
