/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface ImageSourceData {
	$transformer?: {
		formulaVersion?: number;
		/**
		 * parent contract was already merged
		 */
		parentMerged?: boolean;
		/**
		 * is ready to be merged as a final version
		 */
		mergeable?: boolean;
		/**
		 * was merged as a final version
		 */
		merged?: boolean;
		/**
		 * all downstream contracts are merged
		 */
		mergeConfirmed?: boolean;
		/**
		 * this contract is a final version and not a SemVer pre-release
		 */
		finalVersion?: boolean;
		/**
		 * artifact is created
		 */
		artifactReady?: boolean | string;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export interface ImageSourceContractDefinition
	extends ContractDefinition<ImageSourceData> {}

export interface ImageSourceContract extends Contract<ImageSourceData> {}
