/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface OauthProviderData {
	authorizeUrl: string;
	tokenUrl: string;
	clientId: string;
	clientSecret: string;
	integration: string;
	[k: string]: unknown;
}

export type OauthProviderContractDefinition =
	ContractDefinition<OauthProviderData>;

export type OauthProviderContract = Contract<OauthProviderData>;
