/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export type Status =
	| 'Created'
	| 'Discovery'
	| 'Evaluation'
	| 'Committed '
	| 'Closed Won'
	| 'Closed Lost';
export type ExpectedCloseDate = string;
export type EstimatedRecurringValue = number;
export type EstimatedNonRecurringValue = number;
export type TotalValue = number;
export type DeviceType = string;
export type UseCaseS = string;
export type TechStack = string;

export interface OpportunityData {
	status: Status;
	dueDate?: ExpectedCloseDate;
	recurringValue?: EstimatedRecurringValue;
	nonRecurringValue?: EstimatedNonRecurringValue;
	totalValue?: TotalValue;
	device?: DeviceType;
	usecase?: UseCaseS;
	stack?: TechStack;
	participants?: unknown[];
	mentionsUser?: unknown[];
	alertsUser?: unknown[];
	mentionsGroup?: unknown[];
	alertsGroup?: unknown[];
	[k: string]: unknown;
}

export interface OpportunityContractDefinition
	extends ContractDefinition<OpportunityData> {}

export interface OpportunityContract extends Contract<OpportunityData> {}
