/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface PasswordResetData {
	requestedAt?: string;
	expiresAt?: string;
	resetToken?: string;
	[k: string]: unknown;
}

export interface PasswordResetContractDefinition
	extends ContractDefinition<PasswordResetData> {}

export interface PasswordResetContract extends Contract<PasswordResetData> {}
