/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface PasswordResetData {
	requestedAt?: string;
	expiresAt?: string;
	resetToken?: string;
	[k: string]: unknown;
}

export type PasswordResetContractDefinition =
	ContractDefinition<PasswordResetData>;

export type PasswordResetContract = Contract<PasswordResetData>;
