/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface PingData {
	timestamp: string;
	[k: string]: unknown;
}

export interface PingContractDefinition extends ContractDefinition<PingData> {}

export interface PingContract extends Contract<PingData> {}
