/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface ProductData {
	url: string;
	[k: string]: unknown;
}

export interface ProductContractDefinition
	extends ContractDefinition<ProductData> {}

export interface ProductContract extends Contract<ProductData> {}
