/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export type Status =
	| 'implementation'
	| 'all-milestones-complete'
	| 'finalising-and-testing'
	| 'merged'
	| 'released'
	| 'denied-or-failed';

export interface ProjectData {
	description?: string;
	participants?: unknown[];
	mentionsUser?: unknown[];
	alertsUser?: unknown[];
	mentionsGroup?: unknown[];
	alertsGroup?: unknown[];
	status: Status;
	[k: string]: unknown;
}

export type ProjectContractDefinition = ContractDefinition<ProjectData>;

export type ProjectContract = Contract<ProjectData>;
