/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export type Timestamp = string;
export type Actor = string;
export type Message = string;
export type Comment = string;
export type Score = number;
export type EditedAt = string;
export type UsersThatHaveSeenThisRating = string[];

export interface RatingData {
	timestamp: Timestamp;
	actor: Actor;
	payload: {
		mentionsUser?: string[];
		alertsUser?: string[];
		mentionsGroup?: string[];
		alertsGroup?: string[];
		message?: Message;
		comment?: Comment;
		score?: Score;
		[k: string]: unknown;
	};
	edited_at?: EditedAt;
	readBy?: UsersThatHaveSeenThisRating;
	[k: string]: unknown;
}

export type RatingContractDefinition = ContractDefinition<RatingData>;

export type RatingContract = Contract<RatingData>;
