/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export type ExecutionSchedule = {
	[k: string]: unknown;
};

export interface ScheduledActionData {
	options: ActionRequestOptions;
	schedule: ExecutionSchedule;
	[k: string]: unknown;
}
export interface ActionRequestOptions {
	action: string;
	card?: string;
	type?: string;
	arguments: {
		[k: string]: unknown;
	};
	context?: {
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export interface ScheduledActionContractDefinition
	extends ContractDefinition<ScheduledActionData> {}

export interface ScheduledActionContract
	extends Contract<ScheduledActionData> {}
