/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface SubscriptionData {
	[k: string]: unknown;
}

export interface SubscriptionContractDefinition
	extends ContractDefinition<SubscriptionData> {}

export interface SubscriptionContract extends Contract<SubscriptionData> {}
