/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export type CurrentStatus = string;
export type Product = string;
export type Status = 'open' | 'closed' | 'archived';

export interface SupportThreadData {
	category?:
		| 'general'
		| 'customer-success'
		| 'devices'
		| 'fleetops'
		| 'security'
		| 'discussions';
	tags?: string[];
	mirrors?: string[];
	environment?: 'production';
	description?: string;
	inbox?: string;
	statusDescription?: CurrentStatus;
	product?: Product;
	lastMessage?: {
		[k: string]: unknown;
	};
	participants?: unknown[];
	mentionsUser?: unknown[];
	alertsUser?: unknown[];
	mentionsGroup?: unknown[];
	alertsGroup?: unknown[];
	status: Status;
	[k: string]: unknown;
}

export type SupportThreadContractDefinition =
	ContractDefinition<SupportThreadData>;

export type SupportThreadContract = Contract<SupportThreadData>;
