/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface TaskData {
	actor: string;
	input: {
		id: string;
		[k: string]: unknown;
	};
	status: string;
	transformer: {
		id: string;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export interface TaskContractDefinition extends ContractDefinition<TaskData> {}

export interface TaskContract extends Contract<TaskData> {}
