/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface TransformerData {
	$transformer?: {
		formulaVersion?: number;
		/**
		 * parent contract was already merged
		 */
		parentMerged?: boolean;
		/**
		 * all platforms have an image
		 */
		mergeable?: boolean;
		/**
		 * was merged as a final version
		 */
		merged?: boolean;
		/**
		 * all downstream contracts are merged
		 */
		mergeConfirmed?: boolean;
		/**
		 * this contract is a final version and not a SemVer pre-release
		 */
		finalVersion?: boolean;
		/**
		 * artifact is created
		 */
		artifactReady?: boolean | string;
		[k: string]: unknown;
	};
	requirements?: {
		os?: string;
		architecture?: string;
		[k: string]: unknown;
	};
	inputFilter: {
		[k: string]: unknown;
	};
	workerFilter?: {
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export interface TransformerContractDefinition
	extends ContractDefinition<TransformerData> {}

export interface TransformerContract extends Contract<TransformerData> {}
