/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface TransformerWorkerData {
	uuid: string;
	endpoint?: string;
	token?: string;
	transformers?: {
		id?: string;
		ref?: string;
		count?: string;
		[k: string]: unknown;
	}[];
	os?: string;
	architecture?: string;
	cpu_load?: number;
	ram?: {
		available?: number;
		total_mb?: number;
		[k: string]: unknown;
	};
	storage?: {
		available?: number;
		total_mb?: number;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export interface TransformerWorkerContractDefinition
	extends ContractDefinition<TransformerWorkerData> {}

export interface TransformerWorkerContract
	extends Contract<TransformerWorkerData> {}
