/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface WebPushSubscriptionData {
	endpoint: string;
	token: string;
	auth: string;
	[k: string]: unknown;
}

export type WebPushSubscriptionContractDefinition =
	ContractDefinition<WebPushSubscriptionData>;

export type WebPushSubscriptionContract = Contract<WebPushSubscriptionData>;
