###########################################################
# Runtime
###########################################################

FROM resinci/jellyfish-test:1.3.29

WORKDIR /usr/src/jellyfish

COPY package.json package-lock.json /usr/src/jellyfish/
ARG NPM_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc && \
    npm ci && rm -f ~/.npmrc

# Copy in source code and config, and run integration tests
COPY . ./
CMD /bin/bash -c "make test-integration"
