import type { RelationshipContractDefinition } from 'autumndb';

export const relationshipTransformerGeneratedTask: RelationshipContractDefinition =
	{
		slug: 'relationship-transformer-generated-task',
		type: 'relationship@1.0.0',
		name: 'generated',
		data: {
			inverseName: 'was generated by',
			title: 'Task',
			inverseTitle: 'Transformer',
			from: {
				type: 'transformer',
			},
			to: {
				type: 'task',
			},
		},
	};
