import type { RelationshipContractDefinition } from 'autumndb';

export const relationshipTaskGeneratedAny: RelationshipContractDefinition = {
	slug: 'relationship-task-generated-any',
	type: 'relationship@1.0.0',
	name: 'generated',
	data: {
		inverseName: 'was generated by',
		title: 'Task',
		inverseTitle: 'Any',
		from: {
			type: 'task',
		},
		to: {
			type: '*',
		},
	},
};
